### PR TITLE
Add am335x pocketbone

### PR DESCRIPTION
**Pull request by jadonk**
Will test later today or tomorrow.

### CODE REVIEW

**Comment by jadonk** [comment]
@RobertCNelson Sorry, I had a reference mistake I just fixed on this branch. About to boot test this now.

**Comment by jadonk** [comment]
Linux booted, but I think USB isn't coming up due to checks in am335x_evm.sh. Mounting to edit it now. Should I have used a different model? Can we set a default?

**Comment by RobertCNelson** [comment]
usb startup should work now.

**Comment by jadonk** [comment]
This is now tested and ready to merge.

Note: the lack of cpsw being enabled causes some headaches with determining MAC addresses. It might be good to turn part of that back on.

**Pull request merged**
