### PR TITLE
Add bbbmini support

### PR DESCRIPTION
**Pull request by mirkix**

### CODE REVIEW

**Comment by mirkix** [comment]
Hello Robert,
we just worked on the same thing. I think I can close my PR?
Best regards
Mirko

**Comment by RobertCNelson** [comment]
Laughs!!! i just reversed this over lunch today! ;)

https://github.com/RobertCNelson/dtb-rebuilder/commit/335656498265c60d8f0bab28669839aeb9212b60

ps, did you want can0? i noticed the board had it, but your *.dtb i reversed didn't seem to have the can0 interfaced used..

ps2, i have a rt branch now out (lots of people requested it)
https://github.com/RobertCNelson/bb-kernel/tree/am33x-v4.0

Regards,

**Comment by RobertCNelson** [comment]
ps3, your's is actually config-pin complient, i'll revert mine and you pull yours..

**Comment by mirkix** [comment]
I do not use CAN0, there is no CAN0 RX or TX pin on P8 or P9 of the BBB.

**Comment by RobertCNelson** [comment]
i mean, can1, based on
https://github.com/mirkix/BBBMINI/blob/master/doc/pic/bbbmini.pdf

looks like you guys have P9.24/P9.26 wired up, which you can enable via

```
#include "am335x-peripheral-can1.dtsi"
#include "am335x-bone-pinmux-can1.dtsi"
```

It's perfectly fine if nothing is actually connected to the can interface..

Regards,

**Comment by mirkix** [comment]
I can not see the problem with CAN1 even when there is something connected to the can interface.

**Comment by RobertCNelson** [comment]
Doh!
https://github.com/RobertCNelson/dtb-rebuilder/blob/4.0.x/src/arm/am335x-boneblack-bbbmini.dts#L51

Yeah it helps to actually look at the patch, i was still going of the decompiled *.dtb i did over lunch..

Okay, pushing it out as 4.0.6-bone-rt-r6

So you can add "linux-image-4.0.6-bone-rt-r6" and dtb=am335x-boneblack-bbbmini.dtb

Regards,

**Comment by mirkix** [comment]
Just tried 4.0.6-bone-rt-r5, thanks for that!

**Comment by RobertCNelson** [comment]
We were just one config off:
https://github.com/RobertCNelson/bb-kernel/commit/b34da7cea82415a6566a8dcb7cd1651fdc5dfa14
so i defaulted to your setting, so bone-rt-r6 should be drop for your image. ;)
Regards,

**Pull request merged**
